### ISSUE TITLE
pretrained_model

### ISSUE THREAD

**Issue by revolutionaryDijkstra** [SauravSJK/Face-Aging-using-GAN#1]
Hi,
I'm interested in your Face-Aging-using-GAN project.
But I do not have a satisfying GPU to train it.
Can you provide a pretrained model to help me?
I'll be very happy if you can contact me at ewdijkstra67@outlook.com or share it to Google Drive.
Thank you again.

**Comment by SauravSJK** [comment]
Hey,
Sorry, I do not have a pre-trained model and do not have the bandwidth to work on it right now. However, I do plan to fix the issues and add a pre-trained model to the repository soon.
